### ISSUE TITLE
epoch个数设置

### ISSUE THREAD

**Issue by hero-y** [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5#1]
请问在该比赛中，epcoh设置为12和70效果相差的大吗？

**Comment by zhengye1995** [comment]
比赛中缝头、缝头印这两类是长条类型，长宽比例较大，我这里没有调整anchor ratio，所以收敛较慢，一定程度上需要多训练。
如果调整相应anchor应该12 或者 20epoch就可以达到很好效果。
实际比赛中我测试70e比12e会好一些，原因如上
