### ISSUE TITLE
你好，请问一下在测试的时候缺少json文件

### ISSUE THREAD

**Issue by Windight** [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5#15]
缺少以下文件
result_map.bbox.json
result_zj.bbox.json

**Comment by zhengye1995** [comment]
These json files are generated by inference/json2submit1.py and inference/json2submit3.py, maybe you should check the inference process.

**Comment by Windight** [comment]
非常感谢，就是，我想问的是 
inference/json2submit1.py和json2submit3.py中的
test_json = json.load(open('../data/result_map.bbox.json', "r"))
test_json = json.load(open('../data/result_zj.bbox.json', "r"))
result_map.bbox.json和result_zj.bbox.json，是在哪里得到的，
可能是我看错了，但是这两个文件应该不是在这里得到的吧。。

**Comment by zhengye1995** [comment]
> 非常感谢，就是，我想问的是
> inference/json2submit1.py和json2submit3.py中的
> test_json = json.load(open('../data/result_map.bbox.json', "r"))
> test_json = json.load(open('../data/result_zj.bbox.json', "r"))
> result_map.bbox.json和result_zj.bbox.json，是在哪里得到的，
> 可能是我看错了，但是这两个文件应该不是在这里得到的吧。。

yes, you are right. These json files are the raw output from the inference in mmdet.
'result_map.bbox.json' from 
./inference/dist_test.sh config/fabric_defect/cascade_rcnn_r50_fpn_70e.py weights/cascade_rcnn_r50_fpn_70e/latest.pth 1 --json_out data/result_map.json

'results_zj.bbox.json' from 
./inference/dist_test.sh config/fabric_defect/cascade_rcnn_r50_fpn_400.py weights/cascade_rcnn_r50_fpn_400/latest.pth 1 --json_out data/result_zj.json

**Comment by Windight** [comment]
好的，非常感谢
