### ISSUE TITLE
复赛数据集

### ISSUE THREAD

**Issue by Tinagao222** [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5#16]
你好，百度网盘里只有4000多张图片，但我看官网说花色布数据约12000张，请问你有全的复赛数据吗？如果有，可否分享一下，谢谢了

**Comment by zhengye1995** [comment]
Sorry, this is all the data I have, maybe you can contact Tianchi platform for support.
