### ISSUE TITLE
请问一下怎么输入6通道的图片

### ISSUE THREAD

**Issue by Alex-afka** [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5#17]

**Comment by zhengye1995** [comment]
I implement the 6 channels input in the following way:

for the network:

(i) Change the input channel for the first conv layer in backbone from 3 to 6.
(ii) In order to utilize the pre-trained model from COCO dataset, I double repeat the weight of  first conv layer 

for the data:
(i) just concatenate the target image with its template image along the channel dimension ( 2*3=6)

**Comment by Alex-afka** [comment]
thank you for your reply  关于数据集 想询问一下如果只取用几个类别例如5个  该怎么办 我发现如某个图片有很多不同类别的瑕疵

**Comment by zhengye1995** [comment]
You can treat the other classes as the background and just keep the labels for your taget five classes.

**Comment by Alex-afka** [comment]
十分感激你 thankyou 以后可以多多交流

**Comment by Chen-Song** [comment]
@zhengye1995 请问“just concatenate the target image with its template image along the channel dimension ( 2*3=6)”，在config中的体现是：“在train_pipeline中 dict(type='Concat', template_path=data_root + 'template_Images/'),
”吗？因为按照你的数据移动指引，template_Images文件夹下同时包括target image以及template image。

**Comment by Chen-Song** [comment]
@zhengye1995 有一个疑问是在config文件中data的字典构建中，路径使用的是 “img_prefix=data_root + 'defect_Images/',”，按照你的数据移动指引，defect_Images只包括有缺陷的原图，并不包括模板图像。这里怎么能让模型读取到6个通道的融合图像呢？

**Comment by Chen-Song** [comment]
@zhengye1995 可以问一下你们当时使用的mmdetection的版本是多少吗？mmdetection的版本更新比较快。

**Comment by zhengye1995** [comment]
> @zhengye1995 有一个疑问是在config文件中data的字典构建中，路径使用的是 “img_prefix=data_root + 'defect_Images/',”，按照你的数据移动指引，defect_Images只包括有缺陷的原图，并不包括模板图像。这里怎么能让模型读取到6个通道的融合图像呢？

Please refer the code in [here][https://github.com/zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5/blob/40cc4d35df5ff3e5063dc7dd5cc0da829c909adb/mmdet/datasets/pipelines/concat.py#L7]

**Comment by zhengye1995** [comment]
> @zhengye1995 有一个疑问是在config文件中data的字典构建中，路径使用的是 “img_prefix=data_root + 'defect_Images/',”，按照你的数据移动指引，defect_Images只包括有缺陷的原图，并不包括模板图像。这里怎么能让模型读取到6个通道的融合图像呢？

Please refer the code in [Concat](https://github.com/zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5/blob/40cc4d35df5ff3e5063dc7dd5cc0da829c909adb/mmdet/datasets/pipelines/concat.py#L7)

**Comment by zhengye1995** [comment]
> @zhengye1995 可以问一下你们当时使用的mmdetection的版本是多少吗？mmdetection的版本更新比较快。

1.0.0 or 1.1.0

**Comment by Chen-Song** [comment]
@zhengye1995 实际上template_Images文件夹中的原图（也就是待检测图）并没有使用到，使用的是defect_Images文件夹中的原图，concat.py只是使用了里面的模板图像。感谢作者开源这个代码，学到了很多。

**Comment by Alex-afka** [comment]
2021天池大赛你在参加吗 可以加个好友交流下

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CHENSONG <notifications@github.com&gt;
发送时间: 2021年1月9日 21:55
收件人: zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5 <Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5@noreply.github.com&gt;
抄送: Alex-afka <zhuazei_002@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5] 请问一下怎么输入6通道的图片 (#17)





 
@zhengye1995 实际上template_Images文件夹中的原图（也就是待检测图）并没有使用到，使用的是defect_Images文件夹中的原图，concat.py只是使用了里面的模板图像。感谢作者开源这个代码，学到了很多。

**Comment by Chen-Song** [comment]
@Alex-afka 加我vx 13821008662 (不过我是菜鸡)
