### ISSUE TITLE
请问作者当时网络到达多少代数才收敛的？

### ISSUE THREAD

**Issue by Alex-afka** [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5#19]

**Comment by zhengye1995** [comment]
70 epochs, because:
(i) I changed the frist conv layer in backbone, so I need train all backbone(not same as the original cascade rcnn which freezes the frist block in backbone)
(ii) I did not add more anchor to adapt the long strip target
so it needs more training iters to converge
