### ISSUE TITLE
random seed

### ISSUE THREAD

**Issue by bxhandhxb** [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5#2]
hi
Thanks for your generous sharing very much.
I find the seed of your code is random.  Does it have no influence on your results?

**Comment by zhengye1995** [comment]
Yes, I do not set the seed in my code and you can set is by add '--seed' when training.
It should be a little influence on my results, but will not be very large beacause I found a interesting thing that the dataloader load order is same in every epoch, so I guess this will not infuence results so much.

**Comment by zhengye1995** [comment]
The sampling order is deterministic when using distributed training, so it will not influence results very much.

**Comment by bxhandhxb** [comment]
thx~
