### ISSUE TITLE
What should I do to implement the segmenation result?

### ISSUE THREAD

**Issue by ingbeeedd** [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5#21]
I wonder how to approach this project. I think the model already has the segmentation result, isn't it?

**Comment by zhengye1995** [comment]
In this competition, the data does not have annotations for segmentation, therefore, it can just used to train object detection model,  the model can not predict the sementation result.

**Comment by ingbeeedd** [comment]
Thank you
