### ISSUE TITLE
OOM problem when training with only single gpu

### ISSUE THREAD

**Issue by ingbeeedd** [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5#22]
`python train.py ../config/fabric_defect/cascade_rcnn_r50_fpn_70e.py`

Hello, I only have one GPU (RTX2080, 8GB), so I run it on train.py and it doesn't run due to OOM problems. To solve this problem, I think I have to reduce the image size(possible?) or increase the GPU.

Could you tell me if I approach wrong or if there is a way to reduce the size of the image size?
And there is an extra graphics card, RTX3080, so I think we need to run it on CUDA 11.0 and pytorch 1.7 to run it, will this code work? I'd appreciate it if you could let me know the possibility.

Or could Google Cloud Platform be an alternative? I want to know the amount of memory I need.

![image](https://user-images.githubusercontent.com/57895472/108140380-50d76280-7105-11eb-95a3-a2a9005e1967.png)

Thank you

problem error log
![image](https://user-images.githubusercontent.com/57895472/108148086-766b6880-7113-11eb-9c29-bb5a0a834aa4.png)

**Comment by zhengye1995** [comment]
You can change the image size in config file (``img_scale" in ``train_pipeline").
If you want to use cuda11, I suggest you reimplement my model in the the latest version  mmdetection, which can used in cuda11 with torch1.7.1.
In this project, I used 2080Ti, so you need 11GB memory for training.

**Comment by ingbeeedd** [comment]
Thank you for your detailed answers

I finished configuring the environment in cuda11.1+torch1.7, but I got the following error. I think I need to get the mmdet up to date.

`RuntimeError: CUDA error: no kernel image is available for execution on the device`
![image](https://user-images.githubusercontent.com/57895472/108180230-daa91f00-7149-11eb-9a9a-a24a293fe3e9.png)

__In fact, I'm not familiar with mmdet yet, so I'm going to do a transplant while watching the mmdet tutorial. So is there any additional precautions and requirements when transplanting the model to the latest version? (ex. move dataset.py, etc)__

**Comment by ingbeeedd** [comment]
Does `val anno` exist separately? It doesn't exist in the dataset which I downloaded in server. so does it exist? 
Additionaly what kind of process does the testing go back to? Are I going back to the docker environment?

**Comment by zhengye1995** [comment]
In this repo, I used all data to train my model for the final submission, so there are no val anno, you can split val data from training dataset by yourself.

For the testing process, this competition requires us to submit our code in docker to predict the final results for testing data. And the testing data can only attached online in the docker environment, we can not download the testing dataset. You can refer the competition webpage to get more details.

**Comment by ingbeeedd** [comment]
Thank you very much for your answer. By the way, is there a difference between normal and template images?

**Comment by ingbeeedd** [comment]
Can I simply recognize that the template picture is the background?

**Comment by zhengye1995** [comment]
> Thank you very much for your answer. By the way, is there a difference between normal and template images?

I think there are no difference between them.

**Comment by zhengye1995** [comment]
> Can I simply recognize that the template picture is the background?

Yes, of course.

**Comment by ingbeeedd** [comment]
Thank you. I close it
