### ISSUE TITLE
请问您是怎么计算出cas的三个head的iou？

### ISSUE THREAD

**Issue by zhongqiu1245** [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5#23]
您好！
您在readme中说到“根据比赛0.1 0.3 0.5的iou要求, 将cas三个head的iou阈值调整为0.4 0.5 0.6“
请问您是怎么通过（0.1， 0.3，0.5）算出cas的（0.4，0.5，0.6)的呢？能详细的讲解一下吗？
谢谢您！

**Comment by zhengye1995** [comment]
你好，这个没有一个严格的计算，就是一个经验值的设置：
         因为cascade rcnn的原理是逐步的提升iou assign的阈值来获取更好的feature alignment，
所以当比赛的iou要求比较低的时候，我们可以一起降低模型的要求，这个策略往往能提升map，因为根据cascade的论文中的结论，训练时候的iou assign 用多少，测试时候在对应阈值的map就最高，具体你可以阅读论文内容
具体的操作就是rpn 的 anchor assign的阈值会降低，然后cas 三个 rcnn head也同步降低，一般有两套经验值：
1. RPN 阈值：0.6 0.2 0.2， rcnn head 阈值  0.4 0.5 0.6
2. RPN 阈值：0.5 0.2 0.2 ， rcnn head阈值 0.3 0.4 0.5
具体设置可以参见代码中的config配置文件。

**Comment by zhongqiu1245** [comment]
@zhengye1995  谢谢
