### ISSUE TITLE
对于正常图像（不包含缺陷）图像怎么处理的呢

### ISSUE THREAD

**Issue by Chen-Song** [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5#24]
您好，请问对于正常图像（不包含缺陷）图像怎么处理的呢？看了下代码好像直接给排除掉了？

**Comment by zhengye1995** [comment]
Yes, I have tried use the normal image but did not get any improvement, so I just drop them.
