### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by Xixi323** [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5#28]
I only have 1gpu
when I run **CUDA_VISIBLE_DEVICES=0 ./dist_train.sh ../config/fabric_defect/cascade_rcnn_r50_fpn_70e.py 1**
![image](https://user-images.githubusercontent.com/82492656/118979365-f8855a80-b9aa-11eb-9e38-9223435b42a9.png)
how can I fix it?

**Comment by zhengye1995** [comment]
Please use linux~
