### ISSUE TITLE
标注文件对应

### ISSUE THREAD

**Issue by gdgithub123** [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5#29]
您好，这个标注文件里的疵点代号怎么和疵点种类对应呢，如：\u4e09\u4e1d、\u7a00\u5bc6\u6863分别是那个疵点类型呢

**Comment by zhengye1995** [comment]
你好，这些是Unicode编码形式，可以转换为中文查看，例如：

\u866b\u7c98 转换为中文是虫粘

**Comment by gdgithub123** [comment]
收到，非常感谢您！






发件人：zhengye ***@***.***>
发送日期：2022-06-14 11:21:53
收件人：zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5 ***@***.***>
抄送人：gdgithub123 ***@***.***>,Author ***@***.***>
主题：Re: [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5] 标注文件对应 (Issue #29)

你好，这些是Unicode编码形式，可以转换为中文查看，例如：
\u866b\u7c98 转换为中文是虫粘

**Comment by gdgithub123** [comment]
您好，这是我再网上下载到的数据集，不知道跟您的数据集是不是一个，如果不是的话，方便分享一下您的数据集吗





发件人：zhengye ***@***.***>
发送日期：2022-06-14 11:21:53
收件人：zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5 ***@***.***>
抄送人：gdgithub123 ***@***.***>,Author ***@***.***>
主题：Re: [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5] 标注文件对应 (Issue #29)

你好，这些是Unicode编码形式，可以转换为中文查看，例如：
\u866b\u7c98 转换为中文是虫粘

**Comment by zhengye1995** [comment]
数据集下载方式已经在项目介绍中给出了，请自行查看

**Comment by gdgithub123** [comment]
好的，谢谢








发件人：zhengye ***@***.***>
发送日期：2022-06-14 14:24:12
收件人：zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5 ***@***.***>
抄送人：gdgithub123 ***@***.***>,Author ***@***.***>
主题：Re: [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5] 标注文件对应 (Issue #29)

数据集下载方式已经在项目介绍中给出了，请自行查看
