### ISSUE TITLE
数据集内容

### ISSUE THREAD

**Issue by gdgithub123** [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5#30]
您好，我从项目介绍里下载的数据集解压后出现损坏，数据不可用

**Comment by zhengye1995** [comment]
下载后的文件是分卷压缩的形式，请按照分卷压缩文件的解压方式解压，之前有很多人都下载解压过没有问题

**Comment by gdgithub123** [comment]
您好，网上看到天池的数据集有30多种疵点类型，您之前共享的疵点类型是16种，请问您的数据集是怎么处理的呢






发件人：zhengye ***@***.***>
发送日期：2022-06-14 15:36:05
收件人：zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5 ***@***.***>
抄送人：gdgithub123 ***@***.***>,Author ***@***.***>
主题：Re: [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5] 数据集内容 (Issue #30)

下载后的文件是分卷压缩的形式，请按照分卷压缩文件的解压方式解压，之前有很多人都下载解压过没有问题

**Comment by zhengye1995** [comment]
这个比赛有点久远了，我记忆中是比赛的时候，主办方合并了一些相似的类目，所以直接上类别减少了，并不需要我们处理，给定的标签文件几个类就是几类，具体的数据预处理在readme都写了。
