### ISSUE TITLE
数据集中部分标注似乎有问题

### ISSUE THREAD

**Issue by jielyu** [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5#34]
数据集中有三种高度的图像，分别是 1696、1800和1810.
对于高度为1800和1810的，标注框在图像底部时，会被截断为1696.
存在超过1696的情况是因为标注框 [x1, y1, x2, y2] 中的y1没有被截断，只有y2被截断。
大家都是直接用这份数据的标注吗？还是需要进行进行一些调整？

**Comment by zhengye1995** [comment]
抱歉这个比赛太久远了，我不确定是否有你提到的问题，当时大家是直接使用的，如果真的有这个问题，可能更科学的方式是把这些box ignore掉

**Comment by jielyu** [comment]
@zhengye1995  好的，多谢
