### ISSUE TITLE
"CalledProcessError" when training data on my workstation

### ISSUE THREAD

**Issue by YuzhouPeng** [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5#6]
I use a new machine(CentOs7) and the program return CalledProcessError when running dist_train.sh:
![捕获](https://user-images.githubusercontent.com/13601004/71575872-8009c980-2b29-11ea-8ae5-09aeaff6e0d8.JPG)
this is train.sh file:
![捕获1](https://user-images.githubusercontent.com/13601004/71575929-ae87a480-2b29-11ea-950a-8d6ff478ea3e.JPG)
and dist_train.sh:
![捕获2](https://user-images.githubusercontent.com/13601004/71576008-03c3b600-2b2a-11ea-949e-b4091ee2a2ca.JPG)
All dependencies install succeed. cudnn version 7.6.3

Could you please help me figure out the problem? Thank you!

**Comment by YuzhouPeng** [comment]
I use a single RTX 2080 on my machine

**Comment by zhengye1995** [comment]
Hi @YuzhouPeng ,
`Signals.SIGSEGV: 11` seems to be a common bug when you are using different libraries/environments for compiling and running the code. I find a similar issue in other projects such as nvvl, this might give you a hint to check the running/compiling libraries to fix the bug.

And I think you can open a issue in [mmdetection](https://github.com/open-mmlab/mmdetection/issues) , maybe you can find some way to fix it.

**Comment by YuzhouPeng** [comment]
Thank you!
